import type { AppStateCollectionName } from '@appstate/types'
import { WA_APP_STATE_COLLECTIONS } from '@protocol/constants'

export const APP_STATE_DERIVED_KEY_LENGTH = 160
export const APP_STATE_DERIVED_INDEX_KEY_END = 32
export const APP_STATE_DERIVED_VALUE_ENCRYPTION_KEY_END = 64
export const APP_STATE_DERIVED_VALUE_MAC_KEY_END = 96
export const APP_STATE_DERIVED_SNAPSHOT_MAC_KEY_END = 128
export const APP_STATE_DERIVED_PATCH_MAC_KEY_END = 160

export const APP_STATE_VALUE_MAC_LENGTH = 32
export const APP_STATE_MAC_OCTET_LENGTH = 8
export const APP_STATE_IV_LENGTH = 16
export const APP_STATE_LT_HASH_SIZE = 128
export const APP_STATE_POINT_SIZE = 2

export const APP_STATE_EMPTY_LT_HASH = new Uint8Array(APP_STATE_LT_HASH_SIZE)
export const APP_STATE_DEFAULT_COLLECTION_VERSION = 0

export const APP_STATE_DEFAULT_COLLECTIONS: readonly AppStateCollectionName[] = Object.freeze([
    WA_APP_STATE_COLLECTIONS.CRITICAL_UNBLOCK_LOW,
    WA_APP_STATE_COLLECTIONS.CRITICAL_BLOCK,
    WA_APP_STATE_COLLECTIONS.REGULAR_LOW,
    WA_APP_STATE_COLLECTIONS.REGULAR,
    WA_APP_STATE_COLLECTIONS.REGULAR_HIGH
] as const)
